version: '3.9'
networks:
  app_v1_network:
    ipam:
      config:
        - subnet: 172.2.0.0/24

services:
  site:
    build:
      context: .
      dockerfile: dockerfiles/nginx/nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    ports:
      - '8080:80'
    volumes:
      - './src:/var/www/html:delegated'
    depends_on:
      - php
      - mysql
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.11

  mysql:
    image: 'library/mysql:8.0.26'
    restart: unless-stopped
    tty: true
    ports:
      - '3307:3306'
    volumes:
      - './mysql:/var/lib/mysql:delegated'
    environment:
      MYSQL_DATABASE: app_v1_db
      #      MYSQL_USER: root
      #      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.12

  php:
    build:
      context: .
      dockerfile: dockerfiles/php/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - './src:/var/www/html:delegated'
      - './dockerfiles/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:delegated'
      - './dockerfiles/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini'
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.13

  npm:
    image: node:16.13
    build:
      context: .
      dockerfile: dockerfiles/npm/npm.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - './src:/var/www/html'
    ports:
      - '3000:3000'
      - '3001:3001'
    working_dir: /var/www/html
    user: '1000:1000'
    entrypoint: ['npm']
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.14

  composer:
    build:
      context: .
      dockerfile: dockerfiles/php/composer.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - './src:/var/www/html'
    working_dir: /var/www/html
    depends_on:
      - php
    user: '1000:1000'
    entrypoint:
      - composer
      - '--ignore-platform-reqs'
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.15

  artisan:
    build:
      context: .
      dockerfile: dockerfiles/php/php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./src:/var/www/html:delegated
    depends_on:
      - mysql
    working_dir: /var/www/html
    user: '1000:1000'
    entrypoint: ['php', '/var/www/html/artisan']
    networks:
      app_v1_network:
        ipv4_address: 172.2.0.16